### ISSUE TITLE
Support for bs-platform >= 7.1

### ISSUE THREAD

**Issue by kamilkuz** [Astrocoders/reason-apollo-hooks#109]
On bs-platform >= 7.1 library does not compile.
![reason-apollo-hooks-bs-platform](https://user-images.githubusercontent.com/16646714/76243316-72af4080-6238-11ea-949a-ae9b79ef1abe.png)

**Comment by kamilkuz** [comment]
I've just noticed that the problem is in reason-apollo library and issue exist in that library: https://github.com/apollographql/reason-apollo/issues/226

**Comment by bdunn313** [comment]
This was patched 10 days ago in reason-apollo, however since README.md still advises on using v0.18.0 of reason-apollo, the path forward here is unclear. Advice?
