### ISSUE TITLE
Document useSubscription

### ISSUE THREAD

**Issue by bdunn313** [Astrocoders/reason-apollo-hooks#112]
The README should have documentation on how to use `useSubscription` properly. Currently the README does not provide an explanation on how to use this properly, and a newcomer (like myself) to the ReasonReact scene may need a little extra help in the way of examples to get off the ground.

I would love to contribute this myself, but I'm currenlty a bit of a /\/0013 at ReasonML and properly reading type signatures / understanding error messages. Having more examples like this in the docs would be fantastic for understanding and adoption

**Comment by bdunn313** [comment]
Never mind - figured it out,. and created a PR!

**Comment by fakenickels** [comment]
Thanks!!
