### ISSUE TITLE
Support for ~refetchQueries 

### ISSUE THREAD

**Issue by mitel** [Astrocoders/reason-apollo-hooks#13]
Hello,

my use case: 
component has a list of toggle/switchers to enable/disable certain features. Each toggle triggers a mutation. At the same time I need the local cache updated with the result of the mutation on the same page. 

The only way i made it work was with using `refetchQueries`. Probably possible with ReadQuery/WriteQuery but still struggling.

Thanks

**Comment by fakenickels** [comment]
This is part of the #1 issue

**Comment by mitel** [comment]
cool, closing it
