### ISSUE TITLE
What type is returned by Mutation.use()

### ISSUE THREAD

**Issue by lukashambsch** [Astrocoders/reason-apollo-hooks#37]
I have some code like this: `let (createUser, _, _) = CreateMutation.use();` and I want to pass createUser to another function. How can I easily type that function?

I have this now, but I'd rather not have to create it each time I do this.
```
type mutation = (~variables: Js.Json.t=?, ~client: ApolloClient.generatedApolloClient=?,
    ~refetchQueries: ReasonApolloTypes.executionResult =>
                     array(ApolloClient.queryObj)=?,
    unit) =>
    Js.Promise.t(ReasonApolloHooks.Mutation.controledVariantResult(ReactTemplate.Api.Mutations.CreateUserMeasurement.t))
```

With regular reason apollo I was able to type the function argument like this.

```
module CreateMutation = ReasonApollo.CreateMutation(CreateUserMeasurement);
.... other code
let createMeasurement = (userId, mutate: CreateMutation.apolloMutation, state: Types.statsForm) =>
.... rest of function
```

Is anything similar exposed by reason-apollo-hooks?

**Comment by MargaretKrutikova** [comment]
No, there is no type exposed yet, but I just created a PR that adds the type 😄

**Comment by lukashambsch** [comment]
That's amazing! Thanks!

**Comment by lukashambsch** [comment]
Closing since https://github.com/Astrocoders/reason-apollo-hooks/pull/39 added this.
