### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by nirvdrum** [Astrocoders/reason-apollo-hooks#41]
I was recently encountering an issue with `fetchPolicy` not being a valid option. I tried to work out why that might be by starting with the library changelog, in order to see when it was introduced. Unfortunately, there isn't a changelog for this project.

As it turns out, the option only exists in master and, correspondingly, the README only applies to master.

**Comment by fakenickels** [comment]
Hey there! We are indeed thinking in adding one with lerna and conventional commits, we already use this internally and works wonders

**Comment by nirvdrum** [comment]
Cool. I'm unfamiliar with either of those tools. A simple text file indicating high level changes from release-to-release, along with release dates, would be perfectly fine. If you have a tool that simplifies it, even better.

**Comment by fakenickels** [comment]
closing in favor of #48

**Comment by nirvdrum** [comment]
@fakenickels Thanks for addressing, but where can I find the changelog or release notes? I can't find a file with history information anywhere in the repo and the GitHub releases page has something for  2.0.0-beta.1, but there's been nine tagged releases since then without any indication of what's changed.

**Comment by fakenickels** [comment]
We don't have this for old releases, we'll introduce with the new system of packages management
