### ISSUE TITLE
Purpose of Called in variant result

### ISSUE THREAD

**Issue by lukashambsch** [Astrocoders/reason-apollo-hooks#46]
I was looking at adding `NotCalled` to the variant type & noticed the `Called` option on that type already.

What is the use case for the `Called` option?
Don't the `Loading`, `Error`, `Data` options cover the use cases when `Called` would be used?

I'm also trying to make sure there is a use case for `NotCalled` before adding it.

**Comment by fakenickels** [comment]
Indeed it does not make sense! I can't remember why it is there

**Comment by mbirkegaard** [comment]
This was fixed by #60, right?

**Comment by fakenickels** [comment]
Yes! Thanks for reminding
