### ISSUE TITLE
useEffect is called on every re-render when using simple as a dependency

### ISSUE THREAD

**Issue by Pet3ris** [Astrocoders/reason-apollo-hooks#55]
Hi There,

I'm facing an issue very similar to [this one](https://github.com/Astrocoders/reason-apollo-hooks/issues/28).

However, my hook is related to the `simple` argument of the query, not the `full` argument. It does unfortunately trigger the hook on every re-render.

Any thoughts on why that is if the underlying query value is not changing?

**Comment by kamilkuz** [comment]
I think that better to use `full` in useEffect1 argrument. But you can still use `simple` inside.
Try:
```
let (simple, full) = UserQuery.use();
React.useEffect1(
  () => {
    Js.log2("useEffect called", simple);
    None;
  },
  [|full|],
);
```

I tried this and looks like its called only when full is changed, not every rerender. I think its becouse `full` its record which is immutable structure.

**Comment by kamilkuz** [comment]
I probably know why is that:
In Query.re calculation `full` is in React.useMemo which means that it is calculated only when its change. But calulate `simple` is not in React.useMemo - but in my opinion it should be (like in Mutation.re)

**Comment by Pet3ris** [comment]
@kamilkuz - that's AMAZING! 🙌 Thank you - love a simple fix. I will leave it open for now before the authors can verify if it's seen as a bug or not.

**Comment by fakenickels** [comment]
Hey there! Sorry about the delay we have been out for a conference in this weekend and will get back here soon.

I agree that `simple` should be also in a React.useMemo!
