### ISSUE TITLE
Error in the returned response

### ISSUE THREAD

**Issue by LeoLeBras** [Astrocoders/reason-apollo-hooks#6]
Hey ! 👋

This is awesome! Thank you for making this. 🙏

Well, I'm having issues using `useQuery` with this library. 

It seems there is a small bug in the transformation of the graphql response. I always receive `Data(response)` and never `Loading` or `Error`.

By changing that :

```reason
(
    switch (result) {
    | {data: Some(data)} => Data(data)
    | {error: Some(error)} => Error(error)
    | {loading: true} => Loading
    | _ => NoData
    },
    result,
);
```

to :

```reason
(
    switch (result) {
    | {loading: true} => Loading
    | {error: Some(error)} => Error(error)
    | {data: Some(data)} => Data(data)
    | _ => NoData
    },
    result,
  );
```

it works again! (and it seems closer to [the official source](https://github.com/apollographql/reason-apollo/blob/master/src/graphql-types/ReasonApolloQuery.re#L79))

I can create a PR if that's okay with you! 😊

**Comment by baransu** [comment]
I have a fork with the exact same change. What do you think @fakenickels?

**Comment by fakenickels** [comment]
Hey there! Thanks for that catch!
If you guys can send a PR would be much appreciated, I'll merge ASAP
