### ISSUE TITLE
Missing tag for 2.7.0.

### ISSUE THREAD

**Issue by nirvdrum** [Astrocoders/reason-apollo-hooks#62]
NPM has 2.7.0 listed as the most recent release of this project, but there is no corresponding tag for that release. By extension, there are also no release notes for that release.

**Comment by fakenickels** [comment]
Hey there! We indeed did not have pushed that tags. So I just did (https://github.com/Astrocoders/reason-apollo-hooks/releases/tag/v2.7.0). Thanks for pointing that out. We are setting up a better change log system with lerna and conventional commits in the meanwhile

**Comment by fakenickels** [comment]
We'll know be adopting a better release notes format
https://github.com/Astrocoders/reason-apollo-hooks/releases/tag/3.0.0
